### ISSUE TITLE
How to run stats for UDP server?

### ISSUE THREAD

**Issue by d47081** [greatest-ape/aquatic#225]
Can't find in the [readme](https://github.com/greatest-ape/aquatic/blob/master/crates/udp/README.md), how can I access this component from the browser:
https://github.com/greatest-ape/aquatic/tree/master/crates/udp/templates

Should I build additional HTTP server to enable this feature?

**Comment by d47081** [comment]
Well, just found these lines in config:

``` toml
# Print statistics to standard output
print_to_stdout = false
# Save statistics as HTML to a file
write_html_to_file = false
# Path to save HTML file to
html_file_path = "tmp/statistics.html"
# Run a prometheus endpoint
run_prometheus_endpoint = false
# Address to run prometheus endpoint on
prometheus_endpoint_address = "0.0.0.0:9000"
```
Not sure only about the UDP server includes HTTP one, should I make `statistics.html` accessible via nginx or apache?
